local M = {}

M.colors = {
  bg              = "#0F1117",
  bg_alt          = "#161822",
  bg_dark         = "#0A0B10",
  bg_highlight    = "#1C1F2E",

  fg              = "#E8E8F0",
  fg_dim          = "#B0B0C0",
  fg_dark         = "#808090",

  white           = "#FFFFFF",
  white_soft      = "#F0F0F5",
  white_dim       = "#D8D8E0",

  silver          = "#C0C0C8",
  silver_light    = "#D8D8E0",
  silver_dim      = "#A0A0B0",

  green           = "#A8D5BA",
  green_soft      = "#B8E6C8",
  green_dim       = "#88C9A8",
  green_dark      = "#6BA88A",
  green_glow      = "#90D8B0",

  crystal         = "#E0F0FF",
  crystal_light   = "#F0F8FF",
  crystal_dim     = "#B0D4F0",
  crystal_glow    = "#A8E6FF",
  crystal_blue    = "#C8E6F0",

  accent          = "#A8D5BA",
  accent_alt      = "#C8E6F0",

  error           = "#E06C75",
  warning         = "#E5C07B",
  info            = "#A8D5BA",
  hint            = "#C8E6F0",

  border          = "#2C2F3E",
  cursorline      = "#1A1D2A",
  selection       = "#2A3D4A",
  nontext         = "#2C2F3E",
  line_number     = "#3A3D4E",
  comment         = "#5A5D6E",
  string          = "#A8D5BA",
  ["function"]    = "#C8E6F0",
  keyword         = "#E8C8A0",
  conditional     = "#E8C8A0",
  ["repeat"]      = "#E8C8A0",
  number          = "#E0F0FF",
  type            = "#B8E6C8",
  constant        = "#F0F0F5",
  variable        = "#C0C0C8",
  operator        = "#C8C890",
  preproc         = "#B0D4F0",
  special         = "#A8E6FF",
  title           = "#FFFFFF",
  directory       = "#A8D5BA",
  boolean         = "#E0F0FF",
  float           = "#E0F0FF",
  label           = "#C8E6F0",
  include         = "#B0D4F0",
  exception       = "#E5C07B",
  field           = "#C0C0C8",
  parameter       = "#C0C0C8",
  property        = "#A8D5BA",
  constructor     = "#B8E6C8",
  method          = "#C8E6F0",
  struct           = "#B8E6C8",
  namespace       = "#B0D4F0",
  module          = "#B0D4F0",
  macro           = "#C8E6F0",
  diff_add        = "#A8D5BA",
  diff_change     = "#C8E6F0",
  diff_delete     = "#E06C75",
  diff_text       = "#E0F0FF",
}

return M
