local M = {}

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

function M.setup(c)
  -- Editor
  hl("Normal", { fg = c.fg, bg = c.bg })
  hl("NormalFloat", { fg = c.fg, bg = c.bg_alt })
  hl("NormalNC", { fg = c.fg, bg = c.bg })
  hl("FloatBorder", { fg = c.crystal_dim, bg = c.bg_alt })
  hl("Title", { fg = c.white, bold = true })
  hl("EndOfBuffer", { fg = c.bg })
  hl("Cursor", { fg = c.bg, bg = c.crystal_glow })
  hl("CursorLine", { bg = c.cursorline })
  hl("CursorLineNr", { fg = c.crystal, bold = true })
  hl("LineNr", { fg = c.line_number })
  hl("SignColumn", { bg = c.bg })
  hl("ColorColumn", { bg = c.bg_highlight })
  hl("Conceal", { fg = c.comment })
  hl("CursorColumn", { bg = c.cursorline })
  hl("PMenu", { fg = c.fg, bg = c.bg_highlight })
  hl("PMenuSel", { fg = c.bg, bg = c.green })
  hl("PMenuSbar", { bg = c.bg_highlight })
  hl("PMenuThumb", { bg = c.green_dim })
  hl("WildMenu", { fg = c.bg, bg = c.green })
  hl("MatchParen", { fg = c.crystal_glow, bold = true, underline = true })
  hl("NonText", { fg = c.nontext })
  hl("SpecialKey", { fg = c.nontext })
  hl("Visual", { bg = c.selection })
  hl("VisualNOS", { bg = c.selection })
  hl("Search", { fg = c.bg, bg = c.green })
  hl("IncSearch", { fg = c.bg, bg = c.crystal_glow })
  hl("Substitute", { fg = c.bg, bg = c.green_soft })
  hl("Whitespace", { fg = c.nontext })
  hl("Folded", { fg = c.fg_dim, bg = c.bg_highlight })
  hl("FoldColumn", { fg = c.line_number, bg = c.bg })
  hl("DiffAdd", { bg = c.diff_add, fg = c.bg })
  hl("DiffChange", { bg = c.diff_change, fg = c.bg })
  hl("DiffDelete", { bg = c.diff_delete, fg = c.bg })
  hl("DiffText", { bg = c.diff_text, fg = c.bg })
  hl("SpellBad", { sp = c.error, undercurl = true })
  hl("SpellCap", { sp = c.warning, undercurl = true })
  hl("SpellLocal", { sp = c.info, undercurl = true })
  hl("SpellRare", { sp = c.hint, undercurl = true })

  -- Syntax
  hl("Comment", { fg = c.comment, italic = true })
  hl("Constant", { fg = c.constant })
  hl("String", { fg = c.string })
  hl("Character", { fg = c.string })
  hl("Number", { fg = c.number })
  hl("Boolean", { fg = c.boolean })
  hl("Float", { fg = c.float })
  hl("Identifier", { fg = c.variable })
  hl("Function", { fg = c["function"], italic = true })
  hl("Method", { fg = c.method })
  hl("Statement", { fg = c.keyword })
  hl("Conditional", { fg = c.conditional })
  hl("Repeat", { fg = c["repeat"] })
  hl("Label", { fg = c.label })
  hl("Operator", { fg = c.operator })
  hl("Keyword", { fg = c.keyword })
  hl("Exception", { fg = c.exception })
  hl("Include", { fg = c.include })
  hl("PreProc", { fg = c.preproc })
  hl("Define", { fg = c.preproc })
  hl("Macro", { fg = c.macro })
  hl("PreCondit", { fg = c.preproc })
  hl("Type", { fg = c.type })
  hl("StorageClass", { fg = c.type })
  hl("Structure", { fg = c.struct })
  hl("Typedef", { fg = c.type })
  hl("Special", { fg = c.special })
  hl("SpecialChar", { fg = c.special })
  hl("Tag", { fg = c.crystal })
  hl("Delimiter", { fg = c.fg_dim })
  hl("SpecialComment", { fg = c.comment, italic = true })
  hl("Debug", { fg = c.special })
  hl("Underlined", { underline = true })
  hl("Ignore", { fg = c.bg })
  hl("Error", { fg = c.error, bg = c.bg })
  hl("Todo", { fg = c.bg, bg = c.crystal_glow })
  hl("Directory", { fg = c.directory })

  -- Treesitter
  hl("@comment", { fg = c.comment, italic = true })
  hl("@error", { fg = c.error })
  hl("@none", { fg = c.fg })
  hl("@preproc", { fg = c.preproc })
  hl("@define", { fg = c.preproc })
  hl("@operator", { fg = c.operator })

  hl("@punctuation.delimiter", { fg = c.fg_dim })
  hl("@punctuation.bracket", { fg = c.fg_dim })
  hl("@punctuation.special", { fg = c.special })

  hl("@string", { fg = c.string })
  hl("@string.regex", { fg = c.special })
  hl("@string.escape", { fg = c.special })
  hl("@string.special", { fg = c.special })

  hl("@character", { fg = c.string })
  hl("@character.special", { fg = c.special })

  hl("@boolean", { fg = c.boolean })
  hl("@number", { fg = c.number })
  hl("@number.float", { fg = c.float })

  hl("@function", { fg = c["function"], italic = true })
  hl("@function.builtin", { fg = c.special })
  hl("@function.call", { fg = c["function"] })
  hl("@function.macro", { fg = c.macro })
  hl("@method", { fg = c.method })
  hl("@method.call", { fg = c.method })
  hl("@constructor", { fg = c.constructor })
  hl("@parameter", { fg = c.parameter, italic = true })
  hl("@parameter.reference", { fg = c.parameter })

  hl("@keyword", { fg = c.keyword })
  hl("@keyword.function", { fg = c.keyword })
  hl("@keyword.operator", { fg = c.operator })
  hl("@keyword.import", { fg = c.include })
  hl("@keyword.repeat", { fg = c["repeat"] })
  hl("@keyword.return", { fg = c.keyword })
  hl("@keyword.debug", { fg = c.special })
  hl("@keyword.exception", { fg = c.exception })
  hl("@keyword.conditional", { fg = c.conditional })
  hl("@keyword.directive", { fg = c.preproc })
  hl("@keyword.directive.define", { fg = c.preproc })

  hl("@type", { fg = c.type })
  hl("@type.builtin", { fg = c.type })
  hl("@type.definition", { fg = c.type })
  hl("@type.qualifier", { fg = c.type })

  hl("@field", { fg = c.field })
  hl("@property", { fg = c.property })
  hl("@variable", { fg = c.variable })
  hl("@variable.builtin", { fg = c.special })
  hl("@variable.member", { fg = c.field })
  hl("@variable.parameter", { fg = c.parameter, italic = true })

  hl("@constant", { fg = c.constant })
  hl("@constant.builtin", { fg = c.special })
  hl("@constant.macro", { fg = c.macro })

  hl("@label", { fg = c.label })
  hl("@include", { fg = c.include })
  hl("@exception", { fg = c.exception })
  hl("@namespace", { fg = c.namespace })
  hl("@module", { fg = c.module })
  hl("@module.builtin", { fg = c.special })

  hl("@tag", { fg = c.crystal })
  hl("@tag.attribute", { fg = c.field })
  hl("@tag.delimiter", { fg = c.fg_dim })

  hl("@text", { fg = c.fg })
  hl("@text.strong", { bold = true })
  hl("@text.emphasis", { italic = true })
  hl("@text.underline", { underline = true })
  hl("@text.strike", { strikethrough = true })
  hl("@text.title", { fg = c.title, bold = true })
  hl("@text.literal", { fg = c.string })
  hl("@text.uri", { fg = c.crystal_dim, underline = true })
  hl("@text.math", { fg = c.number })
  hl("@text.environment", { fg = c.keyword })
  hl("@text.environment.name", { fg = c.type })
  hl("@text.note", { fg = c.info })
  hl("@text.warning", { fg = c.warning })
  hl("@text.danger", { fg = c.error })
  hl("@text.diff.add", { fg = c.diff_add })
  hl("@text.diff.delete", { fg = c.diff_delete })

  hl("@string.special.url", { fg = c.crystal_dim, underline = true })
  hl("@markup.heading", { fg = c.title, bold = true })
  hl("@markup.raw", { fg = c.string })
  hl("@markup.link", { fg = c.crystal_dim, underline = true })
  hl("@markup.link.label", { fg = c.crystal })
  hl("@markup.list", { fg = c.keyword })
  hl("@markup.quote", { fg = c.comment })

  -- Semantic Tokens
  hl("@lsp.type.class", { fg = c.type })
  hl("@lsp.type.comment", { fg = c.comment, italic = true })
  hl("@lsp.type.decorator", { fg = c.macro })
  hl("@lsp.type.enum", { fg = c.type })
  hl("@lsp.type.enumMember", { fg = c.constant })
  hl("@lsp.type.function", { fg = c["function"] })
  hl("@lsp.type.interface", { fg = c.type })
  hl("@lsp.type.keyword", { fg = c.keyword })
  hl("@lsp.type.macro", { fg = c.macro })
  hl("@lsp.type.method", { fg = c.method })
  hl("@lsp.type.modifier", { fg = c.type })
  hl("@lsp.type.namespace", { fg = c.namespace })
  hl("@lsp.type.number", { fg = c.number })
  hl("@lsp.type.operator", { fg = c.operator })
  hl("@lsp.type.parameter", { fg = c.parameter, italic = true })
  hl("@lsp.type.property", { fg = c.property })
  hl("@lsp.type.selfKeyword", { fg = c.special })
  hl("@lsp.type.string", { fg = c.string })
  hl("@lsp.type.struct", { fg = c.struct })
  hl("@lsp.type.type", { fg = c.type })
  hl("@lsp.type.typeParameter", { fg = c.type })
  hl("@lsp.type.variable", { fg = c.variable })

  -- LSP
  hl("LspReferenceText", { bg = c.selection })
  hl("LspReferenceRead", { bg = c.selection })
  hl("LspReferenceWrite", { bg = c.selection })
  hl("LspSignatureActiveParameter", { fg = c.bg, bg = c.green })

  -- Diagnostics
  hl("DiagnosticError", { fg = c.error })
  hl("DiagnosticWarn", { fg = c.warning })
  hl("DiagnosticInfo", { fg = c.info })
  hl("DiagnosticHint", { fg = c.hint })
  hl("DiagnosticOk", { fg = c.green })
  hl("DiagnosticUnderlineError", { sp = c.error, undercurl = true })
  hl("DiagnosticUnderlineWarn", { sp = c.warning, undercurl = true })
  hl("DiagnosticUnderlineInfo", { sp = c.info, undercurl = true })
  hl("DiagnosticUnderlineHint", { sp = c.hint, undercurl = true })
  hl("DiagnosticSignError", { fg = c.error })
  hl("DiagnosticSignWarn", { fg = c.warning })
  hl("DiagnosticSignInfo", { fg = c.info })
  hl("DiagnosticSignHint", { fg = c.hint })
  hl("DiagnosticFloatingError", { fg = c.error })
  hl("DiagnosticFloatingWarn", { fg = c.warning })
  hl("DiagnosticFloatingInfo", { fg = c.info })
  hl("DiagnosticFloatingHint", { fg = c.hint })
  hl("DiagnosticVirtualTextError", { fg = c.error })
  hl("DiagnosticVirtualTextWarn", { fg = c.warning })
  hl("DiagnosticVirtualTextInfo", { fg = c.info })
  hl("DiagnosticVirtualTextHint", { fg = c.hint })

  -- Telescope
  hl("TelescopeNormal", { fg = c.fg, bg = c.bg_alt })
  hl("TelescopeBorder", { fg = c.crystal_dim, bg = c.bg_alt })
  hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg_highlight })
  hl("TelescopePromptBorder", { fg = c.green, bg = c.bg_highlight })
  hl("TelescopePromptTitle", { fg = c.bg, bg = c.green })
  hl("TelescopeResultsNormal", { fg = c.fg, bg = c.bg_alt })
  hl("TelescopeResultsBorder", { fg = c.crystal_dim, bg = c.bg_alt })
  hl("TelescopeResultsTitle", { fg = c.bg_alt, bg = c.crystal_dim })
  hl("TelescopePreviewNormal", { fg = c.fg, bg = c.bg })
  hl("TelescopePreviewBorder", { fg = c.crystal_dim, bg = c.bg })
  hl("TelescopePreviewTitle", { fg = c.bg, bg = c.crystal_dim })
  hl("TelescopeSelection", { bg = c.selection })
  hl("TelescopeMultiSelection", { fg = c.green })
  hl("TelescopeMatching", { fg = c.crystal_glow, bold = true })

  -- NvimTree
  hl("NvimTreeNormal", { fg = c.fg, bg = c.bg_alt })
  hl("NvimTreeRootFolder", { fg = c.green, bold = true })
  hl("NvimTreeGitDirty", { fg = c.diff_change })
  hl("NvimTreeGitNew", { fg = c.diff_add })
  hl("NvimTreeGitDeleted", { fg = c.diff_delete })
  hl("NvimTreeSymlink", { fg = c.crystal_dim })
  hl("NvimTreeFolderName", { fg = c.directory })
  hl("NvimTreeOpenedFolderName", { fg = c.directory, bold = true })
  hl("NvimTreeEmptyFolderName", { fg = c.fg_dim })
  hl("NvimTreeImageFile", { fg = c.crystal })

  -- Bufferline
  hl("BufferLineTab", { fg = c.fg_dim, bg = c.bg })
  hl("BufferLineTabSelected", { fg = c.fg, bg = c.bg_alt })
  hl("BufferLineTabClose", { fg = c.fg_dim, bg = c.bg_alt })
  hl("BufferLineIndicatorSelected", { fg = c.green, bg = c.bg_alt })
  hl("BufferLineFill", { bg = c.bg })
  hl("BufferLineBackground", { fg = c.fg_dim, bg = c.bg })
  hl("BufferLineBufferVisible", { fg = c.fg, bg = c.bg })
  hl("BufferLineBufferSelected", { fg = c.fg, bg = c.bg_alt })
  hl("BufferLineSeparator", { fg = c.nontext, bg = c.bg })
  hl("BufferLineSeparatorSelected", { fg = c.nontext, bg = c.bg_alt })
  hl("BufferLineSeparatorVisible", { fg = c.nontext, bg = c.bg })
  hl("BufferLineModified", { fg = c.warning })
  hl("BufferLineModifiedSelected", { fg = c.warning })
  hl("BufferLineModifiedVisible", { fg = c.warning })

  -- Statusline
  hl("Statusline", { fg = c.fg, bg = c.bg_alt })
  hl("StatuslineNC", { fg = c.fg_dim, bg = c.bg })
  hl("StatuslineSeparator", { fg = c.green, bg = c.bg_alt })
  hl("StatuslineSeparatorNC", { fg = c.crystal_dim, bg = c.bg })
  hl("StatuslineModeNormal", { fg = c.bg, bg = c.green })
  hl("StatuslineModeInsert", { fg = c.bg, bg = c.crystal_blue })
  hl("StatuslineModeVisual", { fg = c.bg, bg = c.crystal_glow })
  hl("StatuslineModeCommand", { fg = c.bg, bg = c.warning })
  hl("StatuslineModeReplace", { fg = c.bg, bg = c.error })
  hl("StatuslineModeTerminal", { fg = c.bg, bg = c.green_soft })
  hl("StatuslineFilename", { fg = c.white, bg = c.bg_alt })
  hl("StatuslineFilenameNC", { fg = c.fg_dim, bg = c.bg })
  hl("StatuslineInfo", { fg = c.fg_dim, bg = c.bg_alt })
  hl("StatuslineInfoNC", { fg = c.fg_dim, bg = c.bg })

  -- Dashboard
  hl("DashboardHeader", { fg = c.white, bold = true })
  hl("DashboardSubheader", { fg = c.crystal_glow, italic = true })
  hl("DashboardDate", { fg = c.crystal_dim })
  hl("DashboardFlower", { fg = c.green })
  hl("DashboardPetal", { fg = c.green_soft })
  hl("DashboardPetalAlt", { fg = c.crystal_glow })
  hl("DashboardBorder", { fg = c.crystal_dim })
  hl("DashboardKeybind", { fg = c.green })
  hl("DashboardDesc", { fg = c.fg_dim })
  hl("DashboardIcon", { fg = c.crystal })

  -- Which-key
  hl("WhichKey", { fg = c.green, bold = true })
  hl("WhichKeyGroup", { fg = c.crystal_glow })
  hl("WhichKeyDesc", { fg = c.fg_dim })
  hl("WhichKeySeperator", { fg = c.comment })
  hl("WhichKeyFloat", { bg = c.bg_alt })
  hl("WhichKeyBorder", { fg = c.crystal_dim, bg = c.bg_alt })

  -- LSP floating / hover
  hl("LspFloatWinNormal", { fg = c.fg, bg = c.bg_alt })
  hl("LspFloatWinBorder", { fg = c.crystal_dim, bg = c.bg_alt })
end

return M
